[package]
name = "retry_strategy"
version = "0.14.5"
edition = "2021"

[features]
strict = []

[dependencies]
tokio-retry = "0.3.0"

[dev-dependencies]
anyhow = "1"
tokio = { version = "1.36", features = ["full"] }
